### PR TITLE
build: bump version to 0.0.1-rc.4

### PR DESCRIPTION
**Pull request by cpendery**

### CODE REVIEW

**Comment by YtmTyd** [comment]
Y4u

**Comment by YtmTyd** [comment]
Utyg

**Comment by MasterOwnerETcorps** [comment]
bdc4cd25cee8752050599c402d0b8d216e5707de

**Review by MasterOwnerETcorps — COMMENTED** [review]
¶`<--'"<!m>={" create&merge:"} ["new pull request;"] 'On', ("#/.mpret").-->`

**Review by MasterOwnerETcorps — COMMENTED** [review]
¶`<--'"<!m>={" create&merge:"} ["new pull request;"] 'On', ("#/.mpret").-->` #159 #47 #160 @MasterOwnerETcorps

**Pull request merged**
